rtx.bloom.burnIntensity = 1.8
rtx.neeCache.enableModeAfterFirstBounce = 2
rtx.cameraAnimationAmplitude = 0.1
rtx.autoExposure.evMinValue = -1
rtx.autoExposure.enabled = False
rtx.fogRemapColorMultiscatteringScale = 0.5
rtx.minOpaqueDiffuseLobeSamplingProbability = 0.05
rtx.displacement.maxIterations = 40
rtx.restirGI.useSampleStealing = 1
rtx.di.permutationSamplingNthFrame = 1
rtx.froxelMaxDistance = 10000
rtx.camera.freeCameraYaw = -0.275158
rtx.effectLightIntensity = 0.1
rtx.enableVolumetricsInPortals = False
rtx.restirGI.boilingFilterRemoveReservoirThreshold = 30
rtx.enableFog = False
rtx.demodulate.enableDirectLightBoilingFilter = False
rtx.effectLightPlasmaBall = True
rtx.playerModel.horizontalDetectionDistance = 20
rtx.enableDirectTranslucentShadows = True
rtx.denoiser.nrd.timeDeltaBetweenFrames = -1
rtx.di.enableDenoiserConfidence = False
rtx.fogColorScale = 2.89
rtx.di.stealBoundaryPixelSamplesWhenOutsideOfScreen = False
rtx.enableAlwaysCalculateAABB = False
rtx.maxFogDistance = 5000
rtx.fogRemapTransmittanceMeasurementDistanceMax = 20000
rtx.enableIndirectTranslucentShadows = True
rtx.effectLightRadius = 0.01
rtx.emissiveBlendOverrideEmissiveIntensity = 1
rtx.legacyMaterial.emissiveIntensity = 0.01
rtx.enableFirstBounceLobeProbabilityDithering = False
rtx.enableFogRemap = True
rtx.enableUnorderedResolveInIndirectRays = False
rtx.fogRemapTransmittanceMeasurementDistanceMin = 0
rtx.enableVolumetricLighting = True
rtx.usePostFilter = False
rtx.fogRemapMaxDistanceMax = 2000
rtx.fogRemapMaxDistanceMin = 0
rtx.forceCutoutAlpha = 0.6
rtx.russianRouletteMode = 1
rtx.lightConversionDistantLightFixedAngle = 0.01
tx.localtonemap.boostLocalContrast = True
rtx.localtonemap.exposure = 1.9
rtx.localtonemap.exposurePreferenceSigma = 3.9
rtx.localtonemap.finalizeWithACES = False
rtx.localtonemap.highlights = 3.5
rtx.localtonemap.mip = 2
rtx.localtonemap.shadows = 1.8
rtx.minOpaqueSpecularLobeSamplingProbability = 0.05
rtx.stochasticAlphaBlendSearchIteration = 4
rtx.particleSoftnessFactor = 0.1
rtx.postFilterThreshold = 10
rtx.postfx.enableChromaticAberration = False
rtx.stochasticAlphaBlendPlanarDifference = 1
rtx.postfx.enableVignette = False
rtx.postfx.exposureFraction = 0.75
rtx.resolveOpaquenessThreshold = 1
rtx.resolveTransparencyThreshold = 0
rtx.restirGI.boilingFilterMinThreshold = 15
rtx.restirGI.historyDiscardStrength = 10
rtx.restirGI.sampleStealingJitter = 3
rtx.restirGI.useAdaptiveTemporalHistory = False
rtx.restirGI.useDLSSRRCompatibilityMode = True
rtx.restirGI.useVirtualSample = False
rtx.restirGI.validateVisibilityChange = True
rtx.restirGI.virtualSampleMaxDistanceRatio = 0.5
rtx.stochasticAlphaBlendRadianceVolumeMultiplier = 1.2
rtx.skyBrightness = 1.0
rtx.stochasticAlphaBlendNormalSimilarity = 0
rtx.stochasticAlphaBlendOpacityThreshold = 1
rtx.stochasticAlphaBlendUseRadianceVolume = False
rtx.uniqueObjectDistance = 120
rtx.vertexColorStrength = 1
rtx.viewDistance.distanceFadeMax = 10000
rtx.viewDistance.distanceFadeMin = 6000
rtx.viewDistance.noiseScale = 1
rtx.viewModel.enable = True
rtx.viewModel.maxZThreshold = 0.1
rtx.viewModel.scale = 0.69
rtx.volumetricTransmittanceMeasurementDistance = 4000