rtx.skyBrightness = 20
rtx.bloom.burnIntensity = 30
rtx.bloom.luminanceThreshold = 0.0

rtx.volumetrics.enable = True
rtx.volumetrics.maxAccumulationFrames = 24
rtx.volumetrics.froxelDepthSliceDistributionExponent = 2
rtx.volumetrics.froxelMaxDistanceMeters = 50

#rtx.volumetrics.transmittanceColor = 0.880, 0.950, 0.996
rtx.volumetrics.transmittanceMeasurementDistanceMeters = 4.00
rtx.volumetrics.singleScatteringAlbedo = 1.0, 0.790, 0.570
rtx.volumetrics.anisotropy = 0.3
rtx.volumetrics.depthOffset = 1.00

rtx.autoExposure.evMinValue = -0.190
rtx.userBrightness.userBrightness = 70