rtx.skyBrightness = 0.6
rtx.bloom.burnIntensity = 1.4
rtx.bloom.luminanceThreshold = 0.65
rtx.pstrMaxBounces = 4

rtx.volumetrics.enable = True
rtx.volumetrics.maxAccumulationFrames = 24
rtx.volumetrics.froxelDepthSliceDistributionExponent = 2
rtx.volumetrics.froxelMaxDistanceMeters = 50

rtx.volumetrics.transmittanceColor = 0.930, 0.930, 0.930
rtx.volumetrics.transmittanceMeasurementDistanceMeters = 20.00
rtx.volumetrics.singleScatteringAlbedo = 0.950, 0.950, 0.950
rtx.volumetrics.anisotropy = -0.280
rtx.volumetrics.depthOffset = 1.00

rtx.volumetrics.enableFogRemap = False
rtx.volumetrics.enableAtmosphere = False
rtx.volumetrics.enableHeterogeneousFog = False
rtx.dust.enable = False
