rtx.skyBrightness = 1.1
rtx.rayPortalModelNormalAxis = 0.0, 1.0, 0.0
rtx.rayPortalModelWidthAxis = 1.0, 0.0, 0.0
rtx.rayPortalModelHeightAxis = 0.0, 0.0, 1.0
rtx.rayPortalEnabled = True
rtx.rayPortalSamplingWeightMinDistance = 100.0
rtx.rayPortalSamplingWeightMaxDistance = 10000.0
rtx.rayPortalCameraHistoryCorrection = True
rtx.rayPortalCameraInBetweenPortalsCorrection = True
rtx.rayPortalModelTextureHashes = 5EC61BC800744B26, DFDACB6DE1C7741E