rtx.postfx.chromaticAberrationAmount = 0.1

# global
rtx.tonemappingMode = 0
rtx.tonemap.colorGradingEnabled = True
rtx.tonemap.exposureBias = 3.5
rtx.tonemap.saturation = 1
rtx.tonemap.contrast = 1
rtx.tonemap.tonemappingEnabled = True
rtx.tonemap.colorBalance = 0.1, 1, 0.1

rtx.autoExposure.evMinValue = -1.1
rtx.volumetrics.transmittanceMeasurementDistanceMeters = 1000.00
rtx.bloom.burnIntensity = 5
rtx.bloom.luminanceThreshold = 0.0

rtx.userBrightness.userBrightness = 60