# defines all vars that get reset to level state - values are ignored
rtx.postfx.chromaticAberrationAmount = 0.1
rtx.tonemap.exposureBias = 3.5
rtx.tonemap.saturation = 1
rtx.tonemap.contrast = 1
rtx.tonemap.tonemappingEnabled = True
rtx.tonemap.colorBalance = 0.1, 1, 0.1
rtx.autoExposure.evMinValue = 0

rtx.volumetrics.transmittanceMeasurementDistanceMeters = 50.00

rtx.bloom.burnIntensity = 0
rtx.bloom.luminanceThreshold = 0.0

rtx.userBrightness.userBrightness = 50