#rtx.postfx.vignetteIntensity = 50.0
#rtx.postfx.vignetteRadius = 0.0
#rtx.postfx.vignetteSoftness = 0.896

rtx.bloom.burnIntensity = 400
rtx.bloom.luminanceThreshold = 0.0
rtx.pstrMaxBounces = 2

rtx.autoExposure.autoExposureSpeed = 400
rtx.autoExposure.evMinValue = 0.650
rtx.userBrightness.userBrightness = 10

rtx.localtonemap.exposure = 0.45
rtx.localtonemap.shadows = 1.45
rtx.localtonemap.highlights = -2.140
rtx.localtonemap.finalizeWithACES = True

rtx.volumetrics.enable = True
rtx.volumetrics.maxAccumulationFrames = 24
rtx.volumetrics.froxelDepthSliceDistributionExponent = 2
rtx.volumetrics.froxelMaxDistanceMeters = 30

rtx.volumetrics.transmittanceColor = 0.920, 0.930, 0.940
rtx.volumetrics.transmittanceMeasurementDistanceMeters = 0.3
rtx.volumetrics.singleScatteringAlbedo = 0.630, 0.770, 0.780
rtx.volumetrics.anisotropy = 0.270
rtx.volumetrics.depthOffset = 0.60

rtx.volumetrics.enableHeterogeneousFog = True
rtx.volumetrics.noiseFieldOctaves = 4
rtx.volumetrics.noiseFieldDensityScale = 1.58
rtx.volumetrics.noiseFieldDensityExponent = 4.63

#rtx.volumetrics.enableAtmosphere = True
rtx.volumetrics.atmosphereHeightMeters = 2.3

rtx.dust.enable = True
rtx.dust.opacity = 0.3
rtx.dust.anisotropy = 1.0
rtx.dust.minParticleSize = 2.0
rtx.dust.maxParticleSize = 8
rtx.dust.numberOfParticles = 200000
rtx.dust.gravityForce = 10
rtx.dust.useTurbulence = True
rtx.dust.turbulenceAmplitude = 5
rtx.dust.turbulenceFrequency = 0.05
rtx.dust.minSpawnDistance = 10
rtx.dust.maxSpawnDistance = 100
rtx.dust.maxSpeed = 3
rtx.dust.minParticleLife = 0.5
rtx.dust.maxParticleLife = 1.5
rtx.dust.timeScale = 1
rtx.dust.rotationSpeed = 5